name: On Push

on:
  push:
    branches: [ master ]

jobs:
  lint:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup QEMU
        run: |
          sudo apt-get update -y
          sudo apt-get install qemu unzip wget -y

      - name: Setup Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
          unzip packer_1.5.5_linux_amd64.zip
          sudo mv packer /usr/bin
          rm -f packer_1.5.5_linux_amd64.zip

      - name: Build centos-8-stream-amd64
        run: |
          export PACKER_LOG=1
          cd centos-8-stream-amd64
          packer build build.json
          ls -lah output-centos-8-stream-amd64

      - name: Release files
        env:
          FILE_UPLOAD_TOKEN: ${{ secrets.FILE_UPLOAD_TOKEN }}
        run: |
          curl -X POST \
            -F "filename=centos-8-stream-amd64.qcow2" \
            -F "file=@releases/centos-8-stream-amd64.qcow2" \
            -F "token=$FILE_UPLOAD_TOKEN" \
            https://files-upload.indexyz.me/QEMU/Templates
