name: On Push

on:
  push:
    branches: [ master ]

jobs:
  lint:
    name: Build
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache ISO image
        id: cache-primes
        uses: actions/cache@v1
        with:
          path: isos
          key: ${{ runner.os }}-isos

      - name: Download ISO
        run:
          bash scripts/download_iso.sh ./centos-8-stream-amd64

      - name: Build centos-8-stream-amd64
        run: |
          export PACKER_LOG=1
          cd centos-8-stream-amd64
          cloud-localds cloud.img cloud.cfg
          packer build -var 'headless=true' \
            -var-file image.json \
            build.json
          ls -lah output-centos-8-stream-amd64

      - name: Release files
        env:
          FILE_UPLOAD_TOKEN: ${{ secrets.FILE_UPLOAD_TOKEN }}
        run: |
          curl -X POST \
            -F "filename=centos-8-stream-amd64.qcow2" \
            -F "file=@centos-8-stream-amd64/output-centos-8-stream-amd64/packer-centos-8-stream-amd64" \
            -F "token=$FILE_UPLOAD_TOKEN" \
            https://files-api.indexyz.me/QEMU/Templates
