name: VM Build

on:
  push:
    branches: [ master ]
    paths-ignore:
    - Dockerfile
    - scripts/entrypoint.sh

jobs:
  archlinux:
    name: ArchLinux Build
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download ISO
        run:
          bash scripts/download_iso.sh ./archlinux-latest-amd64

      - name: Build archlinux-latest-amd64
        run: |
          export PACKER_LOG=1
          cd archlinux-latest-amd64
          packer build -var 'headless=true' \
            -var-file image.json \
            build.json

      - name: Setup YukiDrive Cli
        run: |
          export YUKI_VERSION=1.0.1
          wget https://drive.yukino.co/api/files/onedrive/YukiDrive/CLI/$YUKI_VERSION/linux-x64.zip
          unzip linux-x64.zip
          rm -f linux-x64.zip
          chmod +x ./linux-x64/YukiDrive.CLI
          ./linux-x64/YukiDrive.CLI --init https://drive.indexyz.me ${{ secrets.FILE_UPLOAD_TOKEN }}

      - name: Release files
        run: |
          mv archlinux-latest-amd64/output/packer-archlinux-latest-amd64 archlinux-latest-amd64.qcow2
          ./linux-x64/YukiDrive.CLI --upload onedrive archlinux-latest-amd64.qcow2 QEMU/Templates

  centos-6:
    name: CentOS 6 Build
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download ISO
        run:
          bash scripts/download_iso.sh ./centos-6-amd64

      - name: Build centos-6-amd64
        run: |
          export PACKER_LOG=1
          cd centos-6-amd64
          packer build -var 'headless=true' \
            -var-file image.json \
            build.json
            
      - name: Setup YukiDrive Cli
        run: |
          export YUKI_VERSION=1.0.1
          wget https://drive.yukino.co/api/files/onedrive/YukiDrive/CLI/$YUKI_VERSION/linux-x64.zip
          unzip linux-x64.zip
          rm -f linux-x64.zip
          chmod +x ./linux-x64/YukiDrive.CLI
          ./linux-x64/YukiDrive.CLI --init https://drive.indexyz.me ${{ secrets.FILE_UPLOAD_TOKEN }}

      - name: Release files
        run: |
          mv centos-6-amd64/output/packer-centos-6-amd64 centos-6-amd64.qcow2
          ./linux-x64/YukiDrive.CLI --upload onedrive centos-6-amd64.qcow2 QEMU/Templates

  centos-7:
    name: CentOS 7 Build
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download ISO
        run:
          bash scripts/download_iso.sh ./centos-7-amd64

      - name: Build centos-7-amd64
        run: |
          export PACKER_LOG=1
          cd centos-7-amd64
          packer build -var 'headless=true' \
            -var-file image.json \
            build.json

      - name: Setup YukiDrive Cli
        run: |
          export YUKI_VERSION=1.0.1
          wget https://drive.yukino.co/api/files/onedrive/YukiDrive/CLI/$YUKI_VERSION/linux-x64.zip
          unzip linux-x64.zip
          rm -f linux-x64.zip
          chmod +x ./linux-x64/YukiDrive.CLI
          ./linux-x64/YukiDrive.CLI --init https://drive.indexyz.me ${{ secrets.FILE_UPLOAD_TOKEN }}

      - name: Release files
        run: |
          mv centos-7-amd64/output/packer-centos-7-amd64 centos-7-amd64.qcow2
          ./linux-x64/YukiDrive.CLI --upload onedrive centos-7-amd64.qcow2 QEMU/Templates

  centos-8-stream:
    name: CentOS 8 Stream Build
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download ISO
        run:
          bash scripts/download_iso.sh ./centos-8-stream-amd64

      - name: Build centos-8-stream-amd64
        run: |
          export PACKER_LOG=1
          cd centos-8-stream-amd64
          cloud-localds cloud.img cloud.cfg
          packer build -var 'headless=true' \
            -var-file image.json \
            build.json

      - name: Setup YukiDrive Cli
        run: |
          export YUKI_VERSION=1.0.1
          wget https://drive.yukino.co/api/files/onedrive/YukiDrive/CLI/$YUKI_VERSION/linux-x64.zip
          unzip linux-x64.zip
          rm -f linux-x64.zip
          chmod +x ./linux-x64/YukiDrive.CLI
          ./linux-x64/YukiDrive.CLI --init https://drive.indexyz.me ${{ secrets.FILE_UPLOAD_TOKEN }}

      - name: Release files
        run: |
          mv centos-8-stream-amd64/output/packer-centos-8-stream-amd64 centos-8-stream-amd64.qcow2
          ./linux-x64/YukiDrive.CLI --upload onedrive centos-8-stream-amd64.qcow2 QEMU/Templates

  ubuntu-18-04:
    name: Ubuntu 18.04 Build
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download ISO
        run:
          bash scripts/download_iso.sh ./ubuntu-18.04-amd64

      - name: Build ubuntu-18.04-amd64
        run: |
          export PACKER_LOG=1
          cd ubuntu-18.04-amd64
          packer build -var 'headless=true' \
            -var-file image.json \
            build.json

      - name: Setup YukiDrive Cli
        run: |
          export YUKI_VERSION=1.0.1
          wget https://drive.yukino.co/api/files/onedrive/YukiDrive/CLI/$YUKI_VERSION/linux-x64.zip
          unzip linux-x64.zip
          rm -f linux-x64.zip
          chmod +x ./linux-x64/YukiDrive.CLI
          ./linux-x64/YukiDrive.CLI --init https://drive.indexyz.me ${{ secrets.FILE_UPLOAD_TOKEN }}

      - name: Release files
        run: |
          mv ubuntu-18.04-amd64/output/packer-ubuntu-18.04-amd64 ubuntu-18.04-amd64.qcow2
          ./linux-x64/YukiDrive.CLI --upload onedrive ubuntu-18.04-amd64.qcow2 QEMU/Templates
