name: VM Build

on:
  push:
    branches: [ master ]
    paths-ignore:
    - Dockerfile
    - scripts/entrypoint.sh

jobs:
  archlinux:
    name: ArchLinux Build
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download ISO
        run:
          bash scripts/download_iso.sh ./archlinux-latest-amd64

      - name: Build archlinux-latest-amd64
        run: |
          export PACKER_LOG=1
          cd archlinux-latest-amd64
          packer build -var 'headless=true' \
            -var-file image.json \
            build.json
      - name: Release files
        env:
          FILE_UPLOAD_TOKEN: ${{ secrets.FILE_UPLOAD_TOKEN }}
        run: |
          curl -X POST \
            -F "filename=archlinux-latest-amd64.qcow2" \
            -F "file=@archlinux-latest-amd64/output/packer-archlinux-latest-amd64" \
            -F "token=$FILE_UPLOAD_TOKEN" \
            https://files-api.indexyz.me/QEMU/Templates

  centos-6:
    name: CentOS 6 Build
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download ISO
        run:
          bash scripts/download_iso.sh ./centos-6-amd64

      - name: Build centos-6-amd64
        run: |
          export PACKER_LOG=1
          cd centos-6-amd64
          packer build -var 'headless=true' \
            -var-file image.json \
            build.json
      - name: Release files
        env:
          FILE_UPLOAD_TOKEN: ${{ secrets.FILE_UPLOAD_TOKEN }}
        run: |
          curl -X POST \
            -F "filename=centos-6-amd64.qcow2" \
            -F "file=@centos-6-amd64/output/packer-centos-6-amd64" \
            -F "token=$FILE_UPLOAD_TOKEN" \
            https://files-api.indexyz.me/QEMU/Templates

  centos-7:
    name: CentOS 7 Build
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download ISO
        run:
          bash scripts/download_iso.sh ./centos-7-amd64

      - name: Build centos-7-amd64
        run: |
          export PACKER_LOG=1
          cd centos-7-amd64
          packer build -var 'headless=true' \
            -var-file image.json \
            build.json
      - name: Release files
        env:
          FILE_UPLOAD_TOKEN: ${{ secrets.FILE_UPLOAD_TOKEN }}
        run: |
          curl -X POST \
            -F "filename=centos-7-amd64.qcow2" \
            -F "file=@centos-7-amd64/output/packer-centos-7-amd64" \
            -F "token=$FILE_UPLOAD_TOKEN" \
            https://files-api.indexyz.me/QEMU/Templates

  centos-8-stream:
    name: CentOS 8 Stream Build
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download ISO
        run:
          bash scripts/download_iso.sh ./centos-8-stream-amd64

      - name: Build centos-8-stream-amd64
        run: |
          export PACKER_LOG=1
          cd centos-8-stream-amd64
          cloud-localds cloud.img cloud.cfg
          packer build -var 'headless=true' \
            -var-file image.json \
            build.json

      - name: Release files
        env:
          FILE_UPLOAD_TOKEN: ${{ secrets.FILE_UPLOAD_TOKEN }}
        run: |
          curl -X POST \
            -F "filename=centos-8-stream-amd64.qcow2" \
            -F "file=@centos-8-stream-amd64/output/packer-centos-8-stream-amd64" \
            -F "token=$FILE_UPLOAD_TOKEN" \
            https://files-api.indexyz.me/QEMU/Templates

  ubuntu-18.04:
    name: Ubuntu 18.04 Build
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download ISO
        run:
          bash scripts/download_iso.sh ./ubuntu-18.04-amd64

      - name: Build ubuntu-18.04-amd64
        run: |
          export PACKER_LOG=1
          cd ubuntu-18.04-amd64
          packer build -var 'headless=true' \
            -var-file image.json \
            build.json

      - name: Release files
        env:
          FILE_UPLOAD_TOKEN: ${{ secrets.FILE_UPLOAD_TOKEN }}
        run: |
          curl -X POST \
            -F "filename=ubuntu-18.04-amd64.qcow2" \
            -F "file=@ubuntu-18.04-amd64/output/packer-ubuntu-18.04-amd64" \
            -F "token=$FILE_UPLOAD_TOKEN" \
            https://files-api.indexyz.me/QEMU/Templates
