name: VM Build

on:
  push:
    branches: [ master ]
    paths-ignore:
    - Dockerfile
    - scripts/entrypoint.sh

jobs:
  vm:
    name: VM Build
    runs-on: [self-hosted]

    strategy:
      matrix:
        template: 
          - 'centos-6-amd64'
          - 'centos-7-amd64'
          - 'centos-8-stream-amd64'
          - 'archlinux-latest-amd64'
          - 'ubuntu-18.04-amd64'
          - 'ubuntu-20.04-amd64'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download ISO
        run:
          bash scripts/download_iso.sh ./${{ matrix.template }}

      - name: Build ${{ matrix.template }}
        run: |
          export PACKER_LOG=1
          cd ${{ matrix.template }}
          packer build -var 'headless=true' \
            -var-file image.json \
            build.json

      - name: Setup YukiDrive Cli
        run: |
          export YUKI_VERSION=1.0.1
          wget https://drive.yukino.co/api/files/onedrive/YukiDrive/CLI/$YUKI_VERSION/linux-x64.zip
          unzip linux-x64.zip
          rm -f linux-x64.zip
          chmod +x ./linux-x64/YukiDrive.CLI
          ./linux-x64/YukiDrive.CLI --init https://drive.indexyz.me ${{ secrets.FILE_UPLOAD_TOKEN }}

      - name: Release files
        run: |
          mv ${{ matrix.template }}/output/packer-${{ matrix.template }} ${{ matrix.template }}.qcow2
          ./linux-x64/YukiDrive.CLI --upload onedrive ${{ matrix.template }}.qcow2 QEMU/Templates
